# <center>Assignment 2

Deadline: Wednesday 19:00 Feb 3, 2021

Name: Alua Bilakhanova (211107012)

**In this assignment you need to work with data from the [worldometers](https://www.worldometers.info/coronavirus/) website. I want you to scrape all 215 countries information about coronavirus cases from the website.** 
The data has to include:
- `Country name`
- `Total cases`
- `Total deaths`
- `Total recovered`
- `Active cases`
- `New cases`
- `New deaths`
- `Total tests`
- `Population`

**You need to use beautiful soup 4 and regular expressions for this task. Save results in csv (txt) file and read this dataset**

Run cell below, if you don't have bs4 library

## Import Statements

In [2]:
from urllib.request import Request, urlopen
from bs4 import BeautifulSoup
import re
import csv
import pandas as pd

## Methods

In [74]:
# request
url = 'https://www.worldometers.info/coronavirus/'
req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
html = urlopen(req)

In [75]:
#saving data in csv format
def save_data(data):
    with open('coronavirus_data.csv', encoding='utf-8', mode='a', newline="") as file:
        writer = csv.writer(file)
#         columns = ["Country_name", "Total_cases", "Total_deaths",
#                          "Total_recovered", "Active_cases", "New_cases",
#                          "New_deaths","Total_tests", "Population"]
#         writer.writerow(columns)
        writer.writerow([data['country_name'],
                                 data['total_cases'],
                                 data['total_deaths'],
                                 data['total_recovered'],
                                 data['active_cases'],
                                 data['new_cases'],
                                 data['new_death'],
                                 data['total_tests'],
                                 data['population'],
                                 ])

In [76]:
#scraping data from the webpage
def parser(html):
    if html.code == 200:
        soup = BeautifulSoup(html.read(), 'html.parser')
        table = soup.find('tbody')
        items = table.find_all('tr')
        for item in items:
            country_name = ''
            total_cases = ''
            new_cases = ''
            total_deaths = ''
            new_deaths = ''
            total_recovered = ''
            active_cases = ''
            total_tests = ''
            population = ''
            count = 0
            tds = item.find_all('td', {'style': re.compile('^font|^text-align:right')})
            if len(tds) == 0:
                continue
            for td in tds:
                count += 1
                if count == 2:
                    country_name = td.get_text().strip()
                elif count == 3:
                    total_cases = td.get_text()
                elif count == 4:
                    new_cases = td.get_text()
                elif count == 5:
                    total_deaths = td.get_text()
                elif count == 6:
                    new_deaths = td.get_text()
                elif count == 7:
                    total_recovered = td.get_text()
                elif count == 9:
                    active_cases = td.get_text()
                elif count == 13:
                    total_tests = td.get_text()
                elif count == 15:
                    population = td.get_text()
            data = {
                'country_name': country_name,
                'total_cases': total_cases,
                'total_deaths': total_deaths,
                'total_recovered': total_recovered,
                'active_cases': active_cases,
                'new_cases': new_cases,
                'new_death': new_deaths,
                'total_tests': total_tests,
                'population': population,
            }
            save_data(data)

In [77]:
#calling the method parser
# parser(html)

In [3]:
# reading the csv file (parsed data)
data = pd.read_csv('coronavirus_data.csv')
data

,Country_name,Total_cases,Total_deaths,Total_recovered,Active_cases,New_cases,New_deaths,Total_tests,Population
0,USA,"78,017,402","926,029","47,998,370","29,093,003",NaN,NaN,"914,397,640","334,104,170"
1,India,"42,272,014","502,905","40,660,202","1,108,907",NaN,NaN,"741,561,587","1,401,680,124"
2,Brazil,"26,536,597","632,289","22,717,907","3,186,401",NaN,NaN,"63,776,166","214,973,669"
3,France,"20,758,371","132,506","14,142,022","6,483,843",NaN,NaN,"231,648,947","65,504,333"
4,UK,"17,803,325","158,318","15,246,943","2,398,064",NaN,NaN,"458,465,073","68,455,848"
...,...,...,...,...,...,...,...,...,...
220,Vanuatu,7,1,6,0,NaN,NaN,"23,000","318,600"
221,Marshall Islands,7,,7,0,NaN,NaN,NaN,"59,828"
222,Saint Helena,2,,2,0,NaN,NaN,NaN,"6,106"
223,Micronesia,1,,1,0,NaN,NaN,NaN,"116,949"
224,China,"106,419","4,636","100,288","1,495",+79,NaN,"160,000,000","1,439,323,776"

In [4]:
#csv reader
# with open('coronavirus_data.csv', mode='r') as file:
#     data = csv.reader(file)
#     for row in data:
#         print(row)

['Country_name', 'Total_cases', 'Total_deaths', 'Total_recovered', 'Active_cases', 'New_cases', 'New_deaths', 'Total_tests', 'Population']
['USA', '78,017,402', '926,029 ', '47,998,370', '29,093,003', '', '', '914,397,640', '334,104,170 ']
['India', '42,272,014', '502,905 ', '40,660,202', '1,108,907', '', '', '741,561,587', '1,401,680,124 ']
['Brazil', '26,536,597', '632,289 ', '22,717,907', '3,186,401', '', '', '63,776,166', '214,973,669 ']
['France', '20,758,371', '132,506 ', '14,142,022', '6,483,843', '', '', '231,648,947', '65,504,333 ']
['UK', '17,803,325', '158,318 ', '15,246,943', '2,398,064', '', '', '458,465,073', '68,455,848 ']
['Russia', '12,982,023', '336,023 ', '10,624,954', '2,021,046', '+171,905', '+609', '263,100,000', '146,034,468 ']
['Turkey', '12,238,501', '88,734 ', '11,413,896', '735,871', '', '', '133,974,200', '85,788,865 ']
['Italy', '11,621,736', '148,771 ', '9,399,717', '2,073,248', '', '', '176,176,489', '60,319,735 ']
['Germany', '11,071,070', '119,368 ', '8,142,100', '2,809,602', '+11,197', '+2', '89,622,218', '84,212,064 ']
['Spain', '10,274,653', '94,235 ', '6,573,471', '3,606,947', '', '', '66,213,858', '46,783,720 ']
['Argentina', '8,589,879', '122,684 ', '8,165,948', '301,247', '', '', '33,024,212', '45,858,367 ']
['Iran', '6,619,085', '132,934 ', '6,171,587', '314,564', '+39,819', '+104', '45,505,835', '85,710,180 ']
['Colombia', '5,966,706', '135,757 ', '5,757,588', '73,361', '', '', '32,460,044', '51,749,299 ']
['Poland', '5,188,184', '106,607 ', '4,330,328', '751,249', '+24,404', '+10', '31,560,615', '37,780,363 ']
['Mexico', '5,151,525', '309,546 ', '4,316,077', '525,902', '+10,234', '+129', '14,420,955', '131,096,820 ']
['Netherlands', '4,969,660', '21,336 ', '3,289,330', '1,658,994', '+77,619', '+4', '21,107,399', '17,195,461 ']
['Indonesia', '4,542,601', '144,636 ', '4,191,604', '206,361', '+26,121', '+82', '74,892,949', '278,144,234 ']
['Ukraine', '4,307,437', '101,392 ', '3,681,092', '524,953', '+23,378', '+115', '18,603,958', '43,313,820 ']
['South Africa', '3,623,962', '95,835 ', '3,480,249', '47,878', '', '', '22,464,999', '60,503,129 ']
['Philippines', '3,616,387', '54,538 ', '3,445,129', '116,720', '+6,835', '+12', '27,558,948', '111,910,688 ']
['Peru', '3,363,489', '206,984 ', 'N/A', 'N/A', '', '', '25,933,414', '33,705,451 ']
['Japan', '3,300,589', '19,324 ', '2,450,601', '830,664', '+92,865', '+67', '34,930,054', '125,857,649 ']
['Belgium', '3,296,038', '29,227 ', '2,177,765', '1,089,046', '', '', '30,615,667', '11,670,224 ']
['Czechia', '3,243,698', '37,478 ', '2,915,178', '291,042', '+9,060', '+10', '51,045,595', '10,740,731 ']
['Israel', '3,196,548', '9,180 ', '2,839,623', '347,745', '', '', '41,373,364', '9,326,000 ']
['Canada', '3,125,330', '34,722 ', '2,912,207', '178,401', '', '', '56,795,249', '38,270,858 ']
['Portugal', '2,915,971', '20,222 ', '2,266,939', '628,810', '', '', '33,409,187', '10,149,191 ']
['Malaysia', '2,914,220', '32,034 ', '2,812,614', '69,572', '', '', '44,986,306', '33,028,384 ']
['Australia', '2,750,562', '4,243 ', '2,466,254', '280,065', '+21,155', '+42', '61,690,281', '25,972,513 ']
['Thailand', '2,507,471', '22,306 ', '2,392,384', '92,781', '+10,470', '+12', '17,270,775', '70,079,878 ']
['Switzerland', '2,423,270', '12,909 ', '1,509,734', '900,627', '+9,395', '+1', '17,536,943', '8,755,750 ']
['Romania', '2,418,779', '60,723 ', '1,990,254', '367,802', '+16,958', '+81', '19,733,542', '19,032,577 ']
['Chile', '2,371,833', '39,987 ', '1,781,084', '550,762', '', '', '30,693,072', '19,378,372 ']
['Vietnam', '2,358,786', '38,424 ', '2,122,380', '197,982', '+16,815', '+100', '77,341,557', '98,737,845 ']
['Sweden', '2,287,785', '16,143 ', '1,420,900', '850,742', '', '', '17,101,699', '10,199,889 ']
['Iraq', '2,253,484', '24,543 ', '2,154,262', '74,679', '+5,285', '+27', '17,595,472', '41,663,189 ']
['Austria', '2,084,227', '14,246 ', '1,719,562', '350,419', '+27,299', '+14', '147,226,437', '9,088,513 ']
['Greece', '2,047,849', '24,094 ', '1,806,264', '217,491', '', '', '58,922,413', '10,341,682 ']
['Denmark', '1,947,091', '3,909 ', '1,377,630', '565,552', '+33,013', '+28', '121,652,229', '5,824,798 ']
['Bangladesh', '1,870,901', '28,627 ', '1,612,057', '230,217', '+9,369', '+38', '12,770,880', '167,310,650 ']
['Serbia', '1,779,782', '14,054 ', '1,487,630', '278,098', '+11,439', '+63', '8,351,232', '8,681,121 ']
['Hungary', '1,650,562', '41,975 ', '1,377,097', '231,490', '+33,716', '+234', '10,320,134', '9,621,147 ']
['Pakistan', '1,463,111', '29,516 ', '1,344,403', '89,192', '+3,338', '+38', '25,422,966', '227,740,176 ']
['Jordan', '1,330,107', '13,320 ', '1,179,709', '137,078', '', '', '15,072,131', '10,364,956 ']
['Georgia', '1,325,838', '15,246 ', '1,106,221', '204,371', '+11,235', '+34', '14,939,001', '3,976,929 ']
['Kazakhstan', '1,270,954', '13,356 ', '1,156,981', '100,617', '', '', '11,575,012', '19,135,477 ']
['Ireland', '1,205,914', '6,228 ', '924,370', '275,316', '', '', '11,015,471', '5,025,898 ']
['Morocco', '1,147,243', '15,593 ', '1,104,090', '27,560', '', '', '11,237,010', '37,609,421 ']
['Slovakia', '1,127,020', '17,973 ', '903,463', '205,584', '+9,965', '+15', '5,803,851', '5,463,868 ']
['Cuba', '1,053,560', '8,439 ', '1,037,798', '7,323', '', '', '12,786,630', '11,315,567 ']
['S. Korea', '1,044,963', '6,886 ', '654,621', '383,456', '+35,275', '+13', '15,804,065', '51,339,700 ']
['Bulgaria', '995,436', '33,770 ', '702,143', '259,523', '', '', '8,669,990', '6,864,843 ']
['Croatia', '985,050', '14,194 ', '926,278', '44,578', '+1,270', '+57', '4,331,339', '4,064,804 ']
['Lebanon', '971,774', '9,711 ', '682,977', '279,086', '', '', '4,795,578', '6,776,593 ']
['Nepal', '967,427', '11,827 ', '915,489', '40,111', '+1,022', '+13', '5,283,372', '29,973,581 ']
['Tunisia', '944,175', '26,679 ', '831,091', '86,405', '', '', '4,131,634', '12,016,182 ']
['Norway', '893,560', '1,467 ', '88,952', '803,141', '', '', '9,852,076', '5,488,972 ']
['Bolivia', '871,749', '21,129 ', '720,322', '130,298', '', '', '2,653,186', '11,927,347 ']
['UAE', '859,361', '2,265 ', '786,642', '70,454', '+1,704', '+1', '128,621,662', '10,081,287 ']
['Slovenia', '799,955', '5,990 ', '606,198', '187,767', '+5,512', '+15', '2,527,899', '2,079,395 ']
['Belarus', '783,260', '6,159 ', '770,567', '6,534', '+5,869', '+12', '11,967,413', '9,444,356 ']
['Ecuador', '766,398', '34,730 ', 'N/A', 'N/A', '', '', '2,470,170', '18,070,918 ']
['Lithuania', '756,206', '7,999 ', '636,077', '112,130', '+6,463', '+11', '7,423,424', '2,661,578 ']
['Panama', '727,413', '7,844 ', '678,478', '41,091', '', '', '5,313,027', '4,423,239 ']
['Uruguay', '726,042', '6,637 ', '656,137', '63,268', '', '', '5,369,698', '3,492,968 ']
['Costa Rica', '721,971', '7,641 ', '580,204', '134,126', '', '', '3,324,431', '5,168,437 ']
['Saudi Arabia', '712,644', '8,957 ', '670,780', '32,907', '+3,747', '+3', '38,814,099', '35,679,734 ']
['Guatemala', '711,076', '16,501 ', '650,321', '44,254', '', '', '3,658,004', '18,444,714 ']
['Azerbaijan', '703,334', '8,898 ', '648,512', '45,924', '+4,680', '+27', '6,278,899', '10,285,187 ']
['Sri Lanka', '620,732', '15,621 ', '581,659', '23,452', '+2,212', '+26', '6,155,804', '21,556,723 ']
['Paraguay', '607,947', '17,605 ', '533,190', '57,152', '', '', '2,428,300', '7,272,489 ']
['Kuwait', '578,819', '2,510 ', '522,882', '53,427', '', '', '7,110,604', '4,371,440 ']
['Dominican Republic', '562,613', '4,325 ', '553,816', '4,472', '', '', '2,995,816', '11,021,701 ']
['Myanmar', '538,409', '19,310 ', '514,223', '4,876', '+508', '', '6,546,337', '54,992,622 ']
['Finland', '534,790', '2,095 ', '46,000', '486,695', '+19,898', '+37', '9,571,590', '5,554,476 ']
['Palestine', '529,439', '4,897 ', '468,509', '56,033', '', '', '3,078,533', '5,290,691 ']
['Venezuela', '496,283', '5,487 ', '474,087', '16,709', '', '', '3,359,014', '28,307,169 ']
['Moldova', '467,271', '10,768 ', '407,139', '49,364', '', '', '2,833,736', '4,018,979 ']
['Ethiopia', '466,539', '7,363 ', '400,948', '58,228', '', '', '4,391,357', '119,508,124 ']
['Latvia', '453,751', '4,960 ', '330,746', '118,045', '+3,646', '+9', '6,259,259', '1,852,867 ']
['Libya', '452,950', '6,080 ', '401,674', '45,196', '+2,832', '+13', '2,286,483', '7,020,533 ']
['Mongolia', '449,531', '2,127 ', '313,256', '134,148', '+860', '+3', '4,030,048', '3,362,598 ']
['Egypt', '439,651', '22,936 ', '372,332', '44,383', '', '', '3,693,367', '105,416,079 ']
['Bahrain', '421,081', '1,411 ', '358,973', '60,697', '', '', '8,965,358', '1,795,894 ']
['Singapore', '397,823', '871 ', '360,343', '36,609', '', '', '22,779,662', '5,923,856 ']
['Honduras', '397,548', '10,548 ', '127,289', '259,711', '', '', '1,189,896', '10,156,178 ']
['Armenia', '391,588', '8,097 ', '352,985', '30,506', '+1,631', '+11', '2,783,288', '2,972,094 ']
['Estonia', '385,567', '2,065 ', '281,792', '101,710', '+4,621', '+6', '2,913,114', '1,327,961 ']
['Bosnia and Herzegovina', '356,930', '14,800 ', '192,218', '149,912', '+575', '+78', '1,643,253', '3,248,202 ']
['Oman', '354,597', '4,180 ', '328,215', '22,202', '+2,410', '+8', '25,000,000', '5,313,880 ']
['Qatar', '346,546', '652 ', '333,780', '12,114', '+923', '', '3,325,285', '2,807,805 ']
['Kenya', '322,151', '5,621 ', '296,108', '20,422', '+55', '', '3,261,313', '55,661,920 ']
['Zambia', '307,317', '3,933 ', '300,898', '2,486', '+111', '+3', '3,206,432', '19,205,402 ']
['North Macedonia', '278,182', '8,578 ', '257,280', '12,324', '', '', '1,818,882', '2,083,237 ']
['Cyprus', '273,634', '745 ', '124,370', '148,519', '', '', '9,477,138', '1,221,402 ']
['Albania', '264,624', '3,380 ', '247,636', '13,608', '', '', '1,686,583', '2,872,775 ']
['Algeria', '257,976', '6,646 ', '171,541', '79,789', '', '', '230,861', '45,115,385 ']
['Botswana', '256,041', '2,585 ', '248,771', '4,685', '', '', '2,026,898', '2,427,430 ']
['Nigeria', '253,727', '3,139 ', '230,126', '20,462', '', '', '4,116,369', '214,293,255 ']
['Zimbabwe', '230,402', '5,362 ', '221,027', '4,013', '', '', '2,003,328', '15,208,483 ']
['Uzbekistan', '229,628', '1,586 ', '212,649', '15,393', '+832', '+2', '1,377,915', '34,243,909 ']
['RГ©union', '226,005', '531 ', '165,236', '60,238', '', '', '1,424,291', '905,521 ']
['Mozambique', '224,339', '2,183 ', '217,112', '5,044', '', '', '1,236,564', '32,652,551 ']
['Montenegro', '223,462', '2,601 ', '216,382', '4,479', '', '', '1,129,125', '628,193 ']
['Kyrgyzstan', '199,519', '2,905 ', '191,089', '5,525', '+83', '+3', '1,907,195', '6,696,084 ']
['Afghanistan', '166,924', '7,442 ', '147,079', '12,403', '+637', '+8', '866,733', '40,327,717 ']
['Luxembourg', '165,958', '958 ', '133,735', '31,265', '', '', '4,003,503', '642,241 ']
['Uganda', '162,308', '3,561 ', '99,439', '59,308', '+35', '+4', '2,380,897', '48,045,131 ']
['Ghana', '157,646', '1,415 ', '155,124', '1,107', '+105', '+3', '2,264,272', '32,108,370 ']
['Namibia', '156,371', '3,980 ', '148,048', '4,343', '', '', '929,697', '2,614,379 ']
['Maldives', '150,337', '283 ', '132,872', '17,182', '', '', '2,098,363', '555,746 ']
['Laos', '136,720', '574 ', '7,660', '128,486', '+282', '+5', '980,587', '7,444,178 ']
['El Salvador', '135,109', '3,942 ', '120,327', '10,840', '', '', '1,627,890', '6,538,502 ']
['Rwanda', '129,141', '1,446 ', '45,522', '82,173', '', '', '4,570,580', '13,464,607 ']
['Jamaica', '125,993', '2,694 ', '71,439', '51,860', '', '', '808,366', '2,981,821 ']
['Cambodia', '121,881', '3,015 ', '118,212', '654', '+108', '', '2,808,095', '17,088,530 ']
['Cameroon', '116,718', '1,880 ', '106,050', '8,788', '', '', '1,751,774', '27,600,392 ']
['Trinidad and Tobago', '115,270', '3,460 ', '91,414', '20,396', '', '', '587,130', '1,406,730 ']
['Guadeloupe', '113,966', '795 ', '2,250', '110,921', '', '', '830,521', '400,233 ']
['Angola', '98,364', '1,896 ', '95,896', '572', '', '', '1,391,201', '34,497,050 ']
['Martinique', '92,796', '841  ', '104', '91,851', '', '', '602,739', '374,800 ']
['DRC', '85,510', '1,278 ', '50,930', '33,302', '', '', '846,704', '93,904,857 ']
['Senegal', '85,237', '1,956 ', '82,203', '1,078', '+31', '', '989,244', '17,448,007 ']
['Malawi', '84,813', '2,571 ', '70,497', '11,745', '', '', '533,542', '19,918,770 ']
['Ivory Coast', '80,920', '786 ', '78,604', '1,530', '', '', '1,368,984', '27,420,708 ']
['Iceland', '78,201', '50 ', '66,541', '11,610', '+1,367', '+1', '1,638,467', '344,782 ']
['French Guiana', '76,509', '383 ', '11,254', '64,872', '', '', '572,233', '311,036 ']
['Suriname', '75,531', '1,283 ', '49,296', '24,952', '+129', '+4', '219,589', '595,030 ']
['Malta', '69,175', '570 ', '65,862', '2,743', '+175', '+1', '1,211,456', '443,422 ']
['Eswatini', '68,553', '1,378 ', '66,957', '218', '', '', '462,142', '1,179,354 ']
['Fiji', '63,356', '813  ', '60,937', '1,606', '+29', '+2', '493,403', '906,824 ']
['Guyana', '61,600', '1,181 ', '54,745', '5,674', '', '', '517,421', '792,617 ']
['Madagascar', '61,434', '1,307 ', '54,687', '5,440', '', '', '379,426', '28,827,009 ']
['Sudan', '58,874', '3,588 ', '40,329', '14,957', '', '', '562,941', '45,483,322 ']
['Mauritania', '58,458', '967 ', '56,548', '943', '', '', '701,675', '4,844,679 ']
['Cabo Verde', '55,785', '397 ', '55,231', '157', '', '', '400,982', '565,634 ']
['Belize', '53,544', '629 ', '45,711', '7,204', '', '', '471,284', '409,154 ']
['Syria', '51,915', '3,008 ', '40,573', '8,334', '', '', '146,269', '18,179,145 ']
['French Polynesia', '49,521', '636 ', 'N/A', 'N/A', '', '', '', '283,503 ']
['Barbados', '48,239', '286 ', '35,911', '12,042', '', '', '552,200', '287,937 ']
['Gabon', '47,247', '302 ', '42,857', '4,088', '', '', '1,548,158', '2,309,555 ']
['Channel Islands', '43,739', '135 ', '40,278', '3,326', '', '', '1,189,402', '176,423 ']
['Seychelles', '38,120', '157 ', '36,737', '1,226', '+349', '+3', '', '99,320 ']
['CuraГ§ao', '37,809', '246 ', '36,291', '1,272', '', '', '460,624', '165,165 ']
['Burundi', '37,562', '38 ', '773', '36,751', '', '', '345,742', '12,455,734 ']
['Papua New Guinea', '37,390', '597 ', '35,938', '855', '', '', '249,149', '9,217,619 ']
['Andorra', '36,599', '147 ', '34,223', '2,229', '', '', '249,838', '77,463 ']
['Togo', '36,593', '268 ', '33,799', '2,526', '', '', '668,421', '8,588,405 ']
['Mayotte', '36,474', '187 ', '2,964', '33,323', '', '', '176,919', '283,320 ']
['Guinea', '36,270', '432 ', '32,582', '3,256', '+2', '+2', '584,902', '13,701,179 ']
['Aruba', '33,302', '195 ', '32,938', '169', '', '', '177,885', '107,490 ']
['Tanzania', '33,230', '789 ', 'N/A', 'N/A', '', '', '', '62,448,728 ']
['Bahamas', '32,773', '753 ', '25,107', '6,913', '', '', '212,152', '399,247 ']
['Lesotho', '32,258', '694 ', '22,054', '9,510', '', '', '380,776', '2,169,383 ']
['Mali', '30,205', '715 ', '26,813', '2,677', '', '', '601,777', '21,181,396 ']
['Haiti', '29,715', '804 ', '24,831', '4,080', '', '', '132,422', '11,624,569 ']
['New Caledonia', '28,628', '284 ', '16,131', '12,213', '+2,848', '', '98,964', '289,883 ']
['Mauritius', '26,865', '762 ', '25,684', '419', '+180', '', '358,675', '1,275,141 ']
['Benin', '26,498', '163 ', '25,506', '829', '', '', '604,310', '12,629,899 ']
['Somalia', '26,067', '1,335 ', '13,182', '11,550', '', '', '400,466', '16,600,677 ']
['Faeroe Islands', '24,006', '20 ', '7,693', '16,293', '', '', '759,000', '49,160 ']
['Congo', '23,705', '371 ', '20,178', '3,156', '', '', '347,815', '5,734,845 ']
['Isle of Man', '21,889', '73 ', '21,340', '476', '', '', '150,753', '85,752 ']
['Saint Lucia', '21,513', '341 ', '17,841', '3,331', '', '', '128,357', '184,968 ']
['Burkina Faso', '20,679', '372 ', '20,227', '80', '', '', '244,764', '21,817,822 ']
['Timor-Leste', '20,501', '122 ', '19,768', '611', '+98', '', '236,137', '1,358,538 ']
['Taiwan', '19,192', '851 ', '17,100', '1,241', '+49', '', '10,656,600', '23,885,665 ']
['Brunei', '18,152', '98 ', '16,178', '1,876', '+368', '', '705,356', '444,171 ']
['New Zealand', '17,988', '53 ', '15,228', '2,707', '+215', '', '6,168,565', '5,002,100 ']
['Nicaragua', '17,709', '217 ', '4,225', '13,267', '', '', '', '6,750,455 ']
['Tajikistan', '17,347', '124 ', '17,195', '28', '', '', '', '9,879,581 ']
['South Sudan', '16,833', '137 ', '13,077', '3,619', '', '', '325,097', '11,403,365 ']
['Hong Kong', '16,022', '213 ', '13,232', '2,577', '+614', '', '34,860,499', '7,594,161 ']
['Cayman Islands', '15,934', '15 ', '8,553', '7,366', '', '', '215,963', '66,955 ']
['Equatorial Guinea', '15,845', '182 ', '15,521', '142', '', '', '273,437', '1,476,499 ']
['Djibouti', '15,510', '189 ', '15,291', '30', '', '', '276,309', '1,010,947 ']
['CAR', '14,023', '110 ', '6,859', '7,054', '', '', '81,294', '4,963,856 ']
['Gibraltar', '13,740', '101 ', '12,557', '1,082', '+85', '', '496,695', '33,675 ']
['San Marino', '12,884', '109 ', '11,132', '1,643', '', '', '125,140', '34,045 ']
['Grenada', '12,862', '211 ', '12,003', '648', '', '', '129,263', '113,356 ']
['Gambia', '11,880', '364 ', '11,461', '55', '', '', '135,608', '2,524,990 ']
['Yemen', '11,166', '2,028 ', '7,183', '1,955', '', '', '265,253', '30,874,517 ']
['Bermuda', '10,921', '118 ', '10,332', '471', '', '', '764,368', '61,910 ']
['Greenland', '10,821', '6 ', '2,761', '8,054', '', '', '164,926', '56,927 ']
['Liechtenstein', '9,764', '74 ', '9,338', '352', '+92', '', '80,413', '38,303 ']
['Dominica', '9,722', '51 ', '8,666', '1,005', '', '', '152,095', '72,272 ']
['Eritrea', '9,637', '100 ', '9,376', '161', '', '', '23,693', '3,624,817 ']
['Saint Martin', '9,439', '61  ', '1,399', '7,979', '', '', '78,366', '39,719 ']
['Sint Maarten', '9,396', '81 ', '8,863', '452', '', '', '62,056', '43,654 ']
['Monaco', '8,770', '46 ', '8,391', '333', '', '', '54,960', '39,687 ']
['Niger', '8,686', '302 ', '8,158', '226', '', '', '219,736', '25,603,825 ']
['Comoros', '7,964', '160 ', '7,670', '134', '+20', '', '', '899,171 ']
['Guinea-Bissau', '7,772', '158 ', '6,825', '789', '+2', '', '119,997', '2,042,238 ']
['Sierra Leone', '7,628', '125 ', 'N/A', 'N/A', '', '', '259,958', '8,235,955 ']
['Liberia', '7,276', '290 ', '5,747', '1,239', '', '', '139,824', '5,247,409 ']
['Caribbean Netherlands', '7,209', '29 ', '6,979', '201', '', '', '30,126', '26,612 ']
['Chad', '7,155', '190 ', '4,874', '2,091', '', '', '191,341', '17,177,837 ']
['Antigua and Barbuda', '6,853', '131 ', '6,400', '322', '', '', '18,901', '99,225 ']
['St. Vincent Grenadines', '6,705', '99 ', '6,170', '436', '', '', '97,310', '111,503 ']
['Bhutan', '6,300', '4 ', '3,808', '2,488', '+208', '', '1,521,167', '785,181 ']
['Sao Tome and Principe', '5,912', '71 ', '5,775', '66', '', '', '29,036', '225,657 ']
['British Virgin Islands', '5,839', '51 ', 'N/A', 'N/A', '', '', '98,247', '30,553 ']
['Turks and Caicos', '5,789', '35 ', '5,620', '134', '+2', '', '419,792', '39,554 ']
['Saint Kitts and Nevis', '5,476', '38 ', '5,247', '191', '', '', '65,141', '53,800 ']
['St. Barth', '3,435', '6 ', 'N/A', 'N/A', '', '', '56,491', '9,925 ']
['Solomon Islands', '3,182', '33 ', '132', '3,017', '', '', '5,117', '713,766 ']
['Palau', '2,716', ' ', '1,289', '1,427', '+160', '', '26,831', '18,232 ']
['Anguilla', '2,384', '8 ', '2,341', '35', '', '', '51,382', '15,217 ']
['Kiribati', '1,744', ' ', '', '1,744', '+201', '', '', '122,376 ']
['Saint Pierre Miquelon', '976', '1 ', '872', '103', '', '', '17,273', '5,749 ']
['Diamond Princess', '712', '13 ', '699', '0', '', '', '', ' ']
['Wallis and Futuna', '454', '7 ', '438', '9', '', '', '20,508', '10,924 ']
['Montserrat', '163', '1 ', '161', '1', '', '', '7,796', '4,997 ']
['Falkland Islands', '89', ' ', 'N/A', 'N/A', '', '', '8,632', '3,642 ']
['Macao', '79', ' ', '79', '0', '', '', '5,217', '663,473 ']
['Samoa', '33', ' ', '3', '30', '', '', '', '200,521 ']
['Vatican City', '29', ' ', '28', '1', '', '', '', '804 ']
['Western Sahara', '10', '1 ', '8', '1', '', '', '', '620,777 ']
['MS Zaandam', '9', '2 ', '7', '0', '', '', '', ' ']
['Tonga', '9', ' ', '2', '7', '', '', '', '107,609 ']
['Vanuatu', '7', '1 ', '6', '0', '', '', '23,000', '318,600 ']
['Marshall Islands', '7', ' ', '7', '0', '', '', '', '59,828 ']
['Saint Helena', '2', ' ', '2', '0', '', '', '', '6,106 ']